baseURL = 'https://lsu.nl/'
title = 'LSU'
theme = 'hugo-universal-theme'
defaultContentLanguage = 'nl'

[params]
    disabled_logo = false

    [languages]
        [languages.nl]
            languageCode = 'nl'
            disabled = false
            languageName = 'Nederlands'
            logo_text = "Leiden Studenten Unie"

            logo = "assets/logo-nl.png"
            logo_small = "assets/logo-nl-small.png"

            contentDir = 'content/nl'

            [[params.menu]]
                name = "Contact"
                url  = "/nl/contact"
                weight = 4

                email = "bestuur@lsbo.net"
                contact_form_ajax = false

                enableRecaptchaInContactForm = false
                googleRecaptchaKey = "site_key_for_google_recaptcha"

            [[params.menu.main]]
                name       = "Thuis"
                identifier = "menu.home"
                url        = "/nl"
                weight     = 1


        [languages.en]
            languageCode = 'en-gb'
            disabled = false
            languageName = 'English'
            logo_text = "Leiden Student Union"

            logo = "assets/logo-en.png"
            logo_small = "assets/logo-en-small.png"

            contentDir = 'content/en'

            [[languages.en.params.menu]]
                name = "Contact"
                url  = "/en/contact"
                weight = 4

            [[languages.en.params.menu.main]]
                name       = "Home"
                identifier = "menu.home"
                url        = "/en"
                weight     = 1